const std = @import("std");

// Build for the `butler` CLI. No external Zig package dependencies, so this
// never touches the network at build time — it works under the nixpkgs Zig
// setup hook (which runs `zig build install --prefix $out`) entirely offline.

// build.zig.zon's minimum_zig_version is advisory only — fail fast with a
// clear message instead of cryptic std-library errors on an old compiler.
comptime {
    const min = std.SemanticVersion{ .major = 0, .minor = 16, .patch = 0 };
    if (@import("builtin").zig_version.order(min) == .lt)
        @compileError("butler requires Zig 0.16.x or newer (see README.md)");
}

// The version is single-sourced from build.zig.zon and injected below as the
// `build_options` module (src/spec.zig reads it). package.nix repeats the
// version for Nix's sake; CI asserts the two agree.
const manifest = @import("build.zig.zon");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const options = b.addOptions();
    options.addOption([]const u8, "version", manifest.version);

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addOptions("build_options", options);

    const exe = b.addExecutable(.{
        .name = "butler",
        .root_module = exe_mod,
    });

    // `zig build install` (also the Nix hook's install phase) places the
    // binary in $prefix/bin/butler.
    b.installArtifact(exe);

    // Install the committed man page to $prefix/share/man/man1/butler.1 so
    // `man butler` works wherever the prefix lands. The file is generated by
    // `zig build gen-docs` (below) and committed; installing the static file
    // keeps the install path trivial and robust (no generator runs in a
    // read-only build sandbox).
    b.installFile("man/butler.1", "share/man/man1/butler.1");

    // Convenience: `zig build run -- <args>` during local development.
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run butler");
    run_step.dependOn(&run_cmd.step);

    // `zig build gen-docs` regenerates man/butler.1 and docs/commands.md from
    // src/spec.zig. A host-target tool that imports the spec as a module (so
    // it need not live under src/). This step is intentionally NOT a
    // dependency of install — generation must not run in the read-only Nix
    // build sandbox.
    const spec_mod = b.createModule(.{
        .root_source_file = b.path("src/spec.zig"),
        .target = b.graph.host,
        .optimize = .Debug,
    });
    spec_mod.addOptions("build_options", options);
    const gendoc = b.addExecutable(.{
        .name = "gendoc",
        .root_module = b.createModule(.{
            .root_source_file = b.path("tools/gendoc.zig"),
            .target = b.graph.host,
            .optimize = .Debug,
        }),
    });
    gendoc.root_module.addImport("spec", spec_mod);
    const run_gendoc = b.addRunArtifact(gendoc);
    run_gendoc.addArgs(&.{ "man/butler.1", "docs/commands.md" });
    const docs_step = b.step("gen-docs", "Regenerate man/butler.1 and docs/commands.md from the spec");
    docs_step.dependOn(&run_gendoc.step);

    // Unit tests. The test block in src/main.zig references every module, so
    // this semantically checks the whole tree; the nixpkgs zig hook runs it
    // as the check phase (all offline).
    const test_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_mod.addOptions("build_options", options);
    const unit_tests = b.addTest(.{ .root_module = test_mod });
    const run_unit_tests = b.addRunArtifact(unit_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_unit_tests.step);
}
